import type { CropTheftResult, FriendFarm, Friendship, PlayerProfile } from '../types/database'
import { normalizeCloudState } from './cloudSaveService'
import { supabase } from './supabaseClient'
import { mapProfile } from './profileService'
const client=()=>{if(!supabase)throw new Error('Supabase chưa được cấu hình.');return supabase}
export const searchPlayers=async(term:string,offset=0):Promise<PlayerProfile[]>=>{const {data,error}=await client().rpc('search_players',{term,page_offset:offset,page_size:20});if(error)throw error;return (data??[]).map(mapProfile)}
export const loadFriendships=async(userId:string):Promise<Friendship[]>=>{const {data,error}=await client().from('friendships').select('id,requester_id,addressee_id,status,created_at,updated_at').or(`requester_id.eq.${userId},addressee_id.eq.${userId}`).order('updated_at',{ascending:false});if(error)throw error;const ids=[...new Set((data??[]).map(row=>row.requester_id===userId?row.addressee_id:row.requester_id))];if(!ids.length)return[];const {data:profiles,error:profileError}=await client().from('profiles').select('id,username,display_name,player_code,avatar_url,level,status,last_online_at').in('id',ids);if(profileError)throw profileError;const byId=new Map((profiles??[]).map(p=>[p.id,mapProfile(p)]));return(data??[]).map(row=>({id:row.id,requesterId:row.requester_id,addresseeId:row.addressee_id,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,other:byId.get(row.requester_id===userId?row.addressee_id:row.requester_id)!}))}
export const sendFriendRequest=async(target:string)=>{const {error}=await client().rpc('send_friend_request',{target});if(error)throw error}
export const respondFriendRequest=async(requestId:string,decision:'accepted'|'rejected'|'blocked')=>{const {error}=await client().rpc('respond_friend_request',{request_id:requestId,decision});if(error)throw error}
export const removeFriend=async(friendId:string)=>{const {error}=await client().rpc('remove_friend',{friend_id:friendId});if(error)throw error}
export const cancelFriendRequest=async(requestId:string)=>{const {error}=await client().rpc('cancel_friend_request',{request_id:requestId});if(error)throw error}
export const loadFriendFarm=async(ownerId:string):Promise<FriendFarm>=>{const api=client(),[{data,error},{data:stolen,error:stolenError}]=await Promise.all([api.rpc('get_friend_farm',{owner_id:ownerId}),api.rpc('get_stolen_crop_ids',{owner_id:ownerId})]);if(error)throw error;if(stolenError)throw stolenError;const value=data as {profile:Record<string,unknown>;state:FriendFarm['state']};return{profile:{id:String(value.profile.id),username:String(value.profile.username),displayName:String(value.profile.displayName),playerCode:String(value.profile.playerCode),avatarUrl:value.profile.avatarUrl?String(value.profile.avatarUrl):null,level:Number(value.profile.level),status:value.profile.status==='online'?'online':'offline',lastOnlineAt:String(value.profile.lastOnlineAt)},state:value.state,stolenCropInstanceIds:Array.isArray(stolen)?stolen.map(String):[]}}

export const stealFriendCrop=async(ownerId:string,plotIndex:number,requestId=crypto.randomUUID()):Promise<CropTheftResult>=>{const {data,error}=await client().rpc('steal_friend_crop',{p_owner_id:ownerId,p_plot_index:plotIndex,p_request_id:requestId});if(error)throw error;const value=data as Omit<CropTheftResult,'state'>&{state:unknown};return{...value,state:normalizeCloudState(value.state)}}
