import { useEffect, useState } from 'react'
import { ArrowLeft, BellRing, Clock3, MapPin, Store } from 'lucide-react'
import { locations, locationById } from '../../config/locations'
import { npcs } from '../../config/npcs'
import { friendshipNames, npcActivityLabels } from '../../config/npcUi'
import { useGameStore } from '../../store/gameStore'
import { NpcInteractionPanel } from './NpcInteractionPanel'
import { BaFarmPanel } from './BaFarmPanel'

export function VillagePage({now,onBack}:{now:number;onBack:()=>void}){const states=useGameStore(s=>s.npcStates),relationships=useGameStore(s=>s.npcRelationships),sync=useGameStore(s=>s.syncNpcStates),[selectedNpc,setSelectedNpc]=useState<string>(),[baFarm,setBaFarm]=useState(false);useEffect(()=>{sync(now);const id=window.setInterval(()=>sync(),30_000);return()=>clearInterval(id)},[sync]);return <main className="village-page"><header className="village-header"><button onClick={onBack}><ArrowLeft/> Nông trại</button><div><span>XÓM HOA NẮNG</span><h1>Xóm nhỏ</h1><p>Mỗi người đều có một ngày bận rộn của riêng mình.</p></div><div className="village-clock"><Clock3/>{new Date(now).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</div></header><section className="village-scene"><div className="village-road"/><div className="square-decor">⛲<small>Bảng tin hôm nay<br/>Hãy chào hỏi hàng xóm!</small></div>{locations.filter(location=>!['player_farm','village_road'].includes(location.id)).map((location,index)=>{const here=npcs.filter(npc=>states[npc.id]?.currentLocationId===location.id);return <button key={location.id} className={`village-location location-${index}`} onClick={()=>location.id==='ba_farm'?setBaFarm(true):here[0]&&setSelectedNpc(here[0].id)}><span>{location.icon}</span><b>{location.name}</b>{location.type==='shop'||location.type==='restaurant'?<em><Store/> Chạm để ghé</em>:null}{here.map(npc=><i key={npc.id} style={{background:npc.spriteConfig.color}} onClick={event=>{event.stopPropagation();setSelectedNpc(npc.id)}}>{npc.spriteConfig.icon}<small>💬</small></i>)}</button>})}{npcs.filter(npc=>states[npc.id]?.currentLocationId==='village_road').map(npc=><button className="walking-npc" key={npc.id} style={{left:`${20+(states[npc.id].movementState?.progress??.5)*55}%`}} onClick={()=>setSelectedNpc(npc.id)}>{npc.spriteConfig.icon}<small>Đang trên đường</small></button>)}</section><section className="neighbor-list"><header><BellRing/> Hàng xóm hôm nay</header>{npcs.map(npc=>{const state=states[npc.id],relation=relationships[npc.id];return <button key={npc.id} onClick={()=>setSelectedNpc(npc.id)}><span style={{background:npc.spriteConfig.color}}>{npc.spriteConfig.icon}</span><div><b>{npc.name}</b><small><MapPin/> {locationById(state?.currentLocationId)?.name}</small><em>{state?npcActivityLabels[state.currentActivity]:''}</em></div><strong>{friendshipNames[relation?.friendshipLevel??0]} · ♥ {relation?.friendshipPoints??0}</strong></button>})}</section><NpcInteractionPanel npcId={selectedNpc} now={now} onClose={()=>setSelectedNpc(undefined)}/><BaFarmPanel open={baFarm} now={now} onClose={()=>setBaFarm(false)}/></main>}

export function VillageDevTools(){const state=useGameStore(),setHour=(hour:number)=>{const current=Date.now()+useGameStore.getState().timeOffsetMs,target=new Date(current);target.setHours(hour,0,0,0);useGameStore.setState(s=>({timeOffsetMs:s.timeOffsetMs+target.getTime()-current}));window.setTimeout(()=>useGameStore.getState().syncNpcStates(),0)},nextDay=()=>{useGameStore.setState(s=>({timeOffsetMs:s.timeOffsetMs+86_400_000}));window.setTimeout(()=>useGameStore.getState().syncNpcStates(),0)};return <details className="village-dev"><summary>🧑‍🔧 DEV NPC</summary><div>{[5,7,12,18,22].map(hour=><button key={hour} onClick={()=>setHour(hour)}>⏰ {hour}:00</button>)}<button onClick={nextDay}>📅 Ngày tiếp</button><button onClick={()=>state.refreshWeather('rain')}>🌧️ Mưa</button><button onClick={()=>state.refreshWeather('sunny')}>☀️ Nắng</button><button onClick={()=>state.devSetNpcLocation('hoa','village_square')}>🚶 Hoa → quảng trường</button><button onClick={()=>state.devSetNpcLocation('ba','ba_farm')}>🚜 Ba → ruộng</button><button onClick={()=>state.devSetShopState('hoa-general','open')}>🏪 Ép tiệm mở</button><button onClick={()=>state.devSetShopState('hoa-general','closed')}>🔒 Ép tiệm đóng</button><button onClick={()=>state.devSetShopState('hoa-general',undefined)}>↩️ Lịch thật</button><button onClick={()=>state.devFriendship('hoa',100)}>♥ +100 Hoa</button><button onClick={()=>state.devFriendship('hoa',0)}>♡ Reset Hoa</button><button onClick={()=>useGameStore.setState(s=>({npcFarmStates:{...s.npcFarmStates,ba:{...s.npcFarmStates.ba,plots:s.npcFarmStates.ba.plots.map(p=>({...p,readyAt:new Date(Date.now()+s.timeOffsetMs).toISOString()}))}}}))}>✅ Chín cây Chú Ba</button><button onClick={state.devResetNpcs}>♻️ Reset NPC</button></div></details>}
