import { useState, type FormEvent } from 'react'
import { CheckCircle2, Cloud, CloudOff, LoaderCircle, LogIn, LogOut, RefreshCw, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth, type SyncStatus } from '../contexts/AuthContext'
import { Modal } from './Modal'

const labels:Record<SyncStatus,string>={disabled:'Chưa cấu hình',loading:'Đang tải cloud',saving:'Đang lưu',synced:'Đã đồng bộ',offline:'Đang offline',error:'Lỗi đồng bộ'}
const StatusIcon=({status}:{status:SyncStatus})=>status==='synced'?<CheckCircle2/>:status==='offline'||status==='error'||status==='disabled'?<CloudOff/>:status==='loading'||status==='saving'?<LoaderCircle className="spin"/>:<Cloud/>

export function AccountPanel({open,onClose}:{open:boolean;onClose:()=>void}){
 const auth=useAuth(),[mode,setMode]=useState<'signin'|'signup'>('signin'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false)
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);try{if(mode==='signin'){await auth.signIn(email,password);toast.success('Đăng nhập thành công! Đang tải nông trại...')}else{const hasSession=await auth.signUp(email,password);toast.success(hasSession?'Tài khoản đã sẵn sàng!':'Hãy mở email để xác nhận tài khoản.')} }catch(error){toast.error(error instanceof Error?error.message:'Không thể xác thực.')}finally{setBusy(false)}}
 return <Modal open={open} title="Tài khoản & Cloud Save" onClose={onClose}>
  {!auth.configured?<div className="cloud-setup"><CloudOff/><h3>Chưa kết nối Supabase</h3><p>Tạo file <code>.env.local</code> từ <code>.env.example</code>, điền URL và anon key, sau đó chạy migration SQL.</p><div><b>1.</b> Tạo project Supabase<br/><b>2.</b> Chạy <code>supabase/migrations/001_game_saves.sql</code><br/><b>3.</b> Khởi động lại <code>npm run dev</code></div></div>
  :auth.session?<div className="account-view"><div className="account-hero"><span>👩‍🌾</span><div><small>ĐANG ĐĂNG NHẬP</small><b>{auth.session.user.email}</b></div></div><div className={`sync-status ${auth.status}`}><StatusIcon status={auth.status}/><div><b>{labels[auth.status]}</b><small>{auth.syncError??(auth.lastSyncedAt?`Lần cuối: ${new Date(auth.lastSyncedAt).toLocaleTimeString('vi-VN')}`:'Nông trại được tự động lưu sau mỗi thao tác.')}</small></div></div><div className="cloud-benefit"><ShieldCheck/><div><b>Dữ liệu riêng tư</b><span>RLS chỉ cho tài khoản này đọc và ghi nông trại của chính bạn.</span></div></div><button className="secondary account-action" disabled={auth.status==='saving'||auth.status==='loading'} onClick={()=>void auth.syncNow()}><RefreshCw/> Đồng bộ ngay</button><button className="danger account-action" onClick={()=>void auth.signOut().then(()=>toast.success('Đã đăng xuất.')).catch(e=>toast.error(e.message))}><LogOut/> Đăng xuất</button></div>
  :<div className="auth-view"><div className="auth-cloud">☁️<span>🌱</span></div><h3>{mode==='signin'?'Mang nông trại theo bạn':'Tạo tài khoản nông dân'}</h3><p>{mode==='signin'?'Đăng nhập để tiếp tục chơi trên bất kỳ thiết bị nào.':'Một tài khoản, một nông trại, mọi thiết bị.'}</p><form onSubmit={submit}><label>Email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="ban@example.com"/></label><label>Mật khẩu<input type="password" required minLength={6} autoComplete={mode==='signin'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Tối thiểu 6 ký tự"/></label><button className="primary" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<LogIn/>} {mode==='signin'?'Đăng nhập':'Tạo tài khoản'}</button></form><button className="auth-switch" onClick={()=>setMode(mode==='signin'?'signup':'signin')}>{mode==='signin'?'Chưa có tài khoản? Đăng ký':'Đã có tài khoản? Đăng nhập'}</button></div>}
 </Modal>
}
