import { useEffect, useState } from 'react'
import { CheckCircle2, Cloud, CloudOff, Copy, LoaderCircle, LogOut, RefreshCw, Save, ShieldCheck } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth, type SyncStatus } from '../contexts/AuthContext'
import { useGameStore } from '../store/gameStore'
import { Modal } from './Modal'
const labels:Record<SyncStatus,string>={disabled:'Chưa cấu hình',loading:'Đang tải cloud',saving:'Đang lưu',synced:'Đã đồng bộ',offline:'Đang offline',error:'Lỗi đồng bộ'}
const StatusIcon=({status}:{status:SyncStatus})=>status==='synced'?<CheckCircle2/>:status==='offline'||status==='error'||status==='disabled'?<CloudOff/>:status==='loading'||status==='saving'?<LoaderCircle className="spin"/>:<Cloud/>
export function AccountPanel({open,onClose}:{open:boolean;onClose:()=>void}){const auth=useAuth(),stats=useGameStore(s=>s.stats),[name,setName]=useState(''),[avatar,setAvatar]=useState(''),[busy,setBusy]=useState(false);useEffect(()=>{setName(auth.profile?.displayName??'');setAvatar(auth.profile?.avatarUrl??'')},[auth.profile]);if(!auth.session)return null;const save=async()=>{if(!name.trim())return toast.error('Tên hiển thị không được để trống.');setBusy(true);try{await auth.updateProfile({displayName:name,avatarUrl:avatar||null});toast.success('Đã cập nhật hồ sơ.')}catch{toast.error('Không thể cập nhật hồ sơ.')}finally{setBusy(false)}};return <Modal open={open} title="Hồ sơ của tôi" onClose={onClose}><div className="account-view"><div className="account-hero"><span>{avatar?<img src={avatar} alt=""/>:'👩‍🌾'}</span><div><small>NGƯỜI CHƠI</small><b>{auth.profile?.displayName}</b><em>@{auth.profile?.username}</em></div></div><div className="profile-code"><span>Mã người chơi</span><b>{auth.profile?.playerCode}</b><button onClick={()=>void navigator.clipboard.writeText(auth.profile?.playerCode??'').then(()=>toast.success('Đã sao chép mã.'))}><Copy/></button></div><div className="profile-stats"><span><b>{auth.profile?.level??1}</b>Cấp độ</span><span><b>{stats.harvested}</b>Đã thu hoạch</span><span><b>{auth.profile?.createdAt?new Date(auth.profile.createdAt).toLocaleDateString('vi-VN'):'—'}</b>Ngày tham gia</span></div><label className="profile-field">Tên hiển thị<input value={name} maxLength={40} onChange={e=>setName(e.target.value)}/></label><label className="profile-field">URL avatar<input value={avatar} onChange={e=>setAvatar(e.target.value)} placeholder="https://..."/></label><button className="primary account-action" disabled={busy} onClick={()=>void save()}>{busy?<LoaderCircle className="spin"/>:<Save/>} Lưu hồ sơ</button><div className={`sync-status ${auth.status}`}><StatusIcon status={auth.status}/><div><b>{labels[auth.status]}</b><small>{auth.syncError??(auth.lastSyncedAt?`Lần cuối: ${new Date(auth.lastSyncedAt).toLocaleTimeString('vi-VN')}`:'Nông trại tự động lưu sau mỗi thao tác.')}</small></div></div><div className="cloud-benefit"><ShieldCheck/><div><b>Dữ liệu riêng tư</b><span>RLS chỉ cho tài khoản này sửa dữ liệu nông trại của mình.</span></div></div><button className="secondary account-action" disabled={auth.status==='saving'||auth.status==='loading'} onClick={()=>void auth.syncNow()}><RefreshCw/> Đồng bộ ngay</button><button className="danger account-action" onClick={()=>void auth.signOut().then(()=>toast.success('Đã đăng xuất.')).catch(e=>toast.error(e.message))}><LogOut/> Đăng xuất</button></div></Modal>}
