import { useState, type FormEvent } from 'react'
import { CloudOff, KeyRound as LockKeyRound, LoaderCircle, Sprout } from 'lucide-react'
import { toast, Toaster } from 'sonner'
import { useAuth } from '../contexts/AuthContext'

export function AuthScreen(){const auth=useAuth(),[mode,setMode]=useState<'login'|'register'>('login'),[busy,setBusy]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[confirm,setConfirm]=useState(''),[username,setUsername]=useState(''),[displayName,setDisplayName]=useState('')
 const submit=async(event:FormEvent)=>{event.preventDefault();if(mode==='register'){if(!displayName.trim())return toast.error('Tên hiển thị không được để trống.');if(!/^[a-zA-Z0-9_]{3,24}$/.test(username))return toast.error('Username cần 3–24 ký tự, chỉ gồm chữ, số hoặc dấu gạch dưới.');if(password.length<6)return toast.error('Mật khẩu phải có ít nhất 6 ký tự.');if(password!==confirm)return toast.error('Hai mật khẩu không giống nhau.')}setBusy(true);try{if(mode==='login')await auth.signIn(email,password);else{const active=await auth.signUp({email,password,username,displayName});toast.success(active?'Đăng ký thành công.':'Đăng ký thành công. Hãy xác nhận email rồi đăng nhập.');if(!active)setMode('login')}}catch(error){if(import.meta.env.DEV)console.error(error);toast.error(error instanceof Error?error.message:'Không thể kết nối máy chủ, vui lòng thử lại.')}finally{setBusy(false)}}
 if(!auth.configured)return <main className="auth-gate"><section><CloudOff/><h1>Chưa kết nối máy chủ</h1><p>Hãy cấu hình <code>VITE_SUPABASE_URL</code>, <code>VITE_SUPABASE_ANON_KEY</code> và chạy hai migration Supabase.</p></section></main>
 return <main className="auth-gate"><Toaster richColors position="top-center"/><section className="auth-card"><div className="auth-brand"><Sprout/><div><b>Nông Trại Vui Vẻ</b><span>Một tài khoản, một nông trại riêng</span></div></div><h1>{mode==='login'?'Chào mừng trở lại':'Tạo nông trại mới'}</h1><form onSubmit={submit}>{mode==='register'&&<><label>Tên hiển thị<input required value={displayName} onChange={e=>setDisplayName(e.target.value)} maxLength={40}/></label><label>Username<input required value={username} onChange={e=>setUsername(e.target.value.replace(/\s/g,''))} minLength={3} maxLength={24} autoCapitalize="none"/></label></>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Mật khẩu<input required type="password" minLength={6} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'}/></label>{mode==='register'&&<label>Nhập lại mật khẩu<input required type="password" minLength={6} value={confirm} onChange={e=>setConfirm(e.target.value)} autoComplete="new-password"/></label>}<button className="primary" disabled={busy}>{busy?<LoaderCircle className="spin"/>:<LockKeyRound/>}{mode==='login'?'Đăng nhập':'Đăng ký'}</button></form>{mode==='login'&&<button className="auth-link" onClick={()=>{if(!email)return toast.info('Nhập email trước khi yêu cầu đặt lại mật khẩu.');void auth.resetPassword(email).then(()=>toast.success('Đã gửi email đặt lại mật khẩu.')).catch(e=>toast.error(e.message))}}>Quên mật khẩu?</button>}<button className="auth-switch" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?'Chưa có tài khoản? Tạo tài khoản':'Đã có tài khoản? Đăng nhập'}</button></section></main>}
