import { useCallback, useEffect, useState } from 'react'
import { Check, Clock3, Search, UserMinus, UserPlus, Users, X } from 'lucide-react'
import { toast } from 'sonner'
import { useAuth } from '../contexts/AuthContext'
import { cancelFriendRequest, loadFriendFarm, loadFriendships, removeFriend, respondFriendRequest, searchPlayers, sendFriendRequest } from '../services/friendService'
import type { FriendFarm, Friendship, PlayerProfile } from '../types/database'
import { Modal } from './Modal'
import { supabase } from '../services/supabaseClient'

type Tab='friends'|'received'|'sent'|'search'
const presence=(profile:PlayerProfile)=>profile.status==='online'?'Đang online':`Hoạt động ${new Date(profile.lastOnlineAt).toLocaleString('vi-VN')}`
export function FriendsPanel({open,onClose,onVisit}:{open:boolean;onClose:()=>void;onVisit:(farm:FriendFarm)=>void}){const {session}=useAuth(),[tab,setTab]=useState<Tab>('friends'),[items,setItems]=useState<Friendship[]>([]),[results,setResults]=useState<PlayerProfile[]>([]),[query,setQuery]=useState(''),[loading,setLoading]=useState(false)
 const refresh=useCallback(async()=>{if(!session)return;setLoading(true);try{setItems(await loadFriendships(session.user.id))}catch{toast.error('Không thể tải danh sách bạn bè.')}finally{setLoading(false)}},[session])
 useEffect(()=>{if(open)void refresh()},[open,refresh])
 useEffect(()=>{const client=supabase;if(!open||!session||!client)return;const channel=client.channel(`friendships:${session.user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'friendships'},()=>void refresh()).subscribe();return()=>{void client.removeChannel(channel)}},[open,refresh,session])
 useEffect(()=>{if(!open||tab!=='search'||query.trim().length<2){setResults([]);return}const id=window.setTimeout(()=>void searchPlayers(query.trim()).then(setResults).catch(()=>toast.error('Không thể tìm người chơi.')),350);return()=>window.clearTimeout(id)},[open,query,tab])
 const act=async(fn:()=>Promise<void>,message:string)=>{try{await fn();toast.success(message);await refresh()}catch(error){toast.error(error instanceof Error?error.message:'Thao tác không thành công.')}}
 const visit=async(id:string)=>{setLoading(true);try{onVisit(await loadFriendFarm(id));onClose()}catch{toast.error('Chỉ có thể ghé thăm nông trại của bạn bè.')}finally{setLoading(false)}}
 const visible=items.filter(item=>tab==='friends'?item.status==='accepted':tab==='received'?item.status==='pending'&&item.addresseeId===session?.user.id:tab==='sent'?item.status==='pending'&&item.requesterId===session?.user.id:false)
 return <Modal open={open} title="Bạn bè" onClose={onClose} wide><div className="social-tabs">{([['friends','Bạn bè'],['received','Đã nhận'],['sent','Đã gửi'],['search','Tìm kiếm']] as const).map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='search'?<><label className="player-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tên, username hoặc mã người chơi"/></label><div className="player-list">{results.map(player=>{const related=items.find(item=>item.other.id===player.id);return <article key={player.id}><span>{player.avatarUrl?<img src={player.avatarUrl} alt=""/>:'👩‍🌾'}</span><div><b>{player.displayName}</b><small>@{player.username} · Cấp {player.level}</small><em>{presence(player)}</em></div><button disabled={Boolean(related)} onClick={()=>void act(()=>sendFriendRequest(player.id),'Đã gửi lời mời kết bạn.')}>{related?'Đã gửi':<><UserPlus/> Kết bạn</>}</button></article>})}{query.length>=2&&!results.length&&!loading&&<p className="empty-social">Không tìm thấy người chơi.</p>}</div></>:<div className="player-list">{visible.map(item=><article key={item.id}><span>{item.other.avatarUrl?<img src={item.other.avatarUrl} alt=""/>:'👩‍🌾'}</span><div><b>{item.other.displayName}</b><small>@{item.other.username} · Cấp {item.other.level}</small><em>{presence(item.other)}</em></div><div className="social-actions">{tab==='friends'&&<><button onClick={()=>void visit(item.other.id)}><Users/> Ghé thăm</button><button className="danger-mini" onClick={()=>confirm(`Hủy kết bạn với ${item.other.displayName}?`)&&void act(()=>removeFriend(item.other.id),'Đã hủy kết bạn.')}><UserMinus/></button></>}{tab==='received'&&<><button onClick={()=>void act(()=>respondFriendRequest(item.id,'accepted'),'Đã chấp nhận lời mời.')}><Check/></button><button onClick={()=>void act(()=>respondFriendRequest(item.id,'rejected'),'Đã từ chối lời mời.')}><X/></button><button className="danger-mini" title="Chặn" onClick={()=>void act(()=>respondFriendRequest(item.id,'blocked'),'Đã chặn người chơi.')}><UserMinus/></button></>}{tab==='sent'&&<><span><Clock3/> Đang chờ</span><button className="danger-mini" onClick={()=>void act(()=>cancelFriendRequest(item.id),'Đã hủy lời mời.')}><X/></button></>}</div></article>)}{!visible.length&&!loading&&<p className="empty-social">Chưa có dữ liệu trong mục này.</p>}</div>}</Modal>}
