import { Backpack, Check, Clock3, Coins, Gem, Leaf, LockKeyhole, Minus, PackageOpen, RotateCcw, ShoppingCart, Sparkles, Star } from 'lucide-react'
import { toast } from 'sonner'
import { crops } from '../config/crops'
import { fertilizers } from '../config/fertilizers'
import { useGameStore } from '../store/gameStore'
import type { FarmPlot } from '../types/game'
import { cropById } from '../config/crops'
import { fertilizerById } from '../config/fertilizers'
import { formatNumber } from '../utils/currency'
import { getCropGrowthState } from '../utils/cropGrowth'
import { formatDuration, formatRemainingTime } from '../utils/time'
import { Modal } from './Modal'

const Qty=({type,id}:{type:'seed'|'produce'|'fertilizer';id:string})=>{const n=useGameStore(s=>s.inventory.find(i=>i.itemType===type&&i.referenceId===id)?.quantity??0);return <span className="qty">x{n}</span>}
const run=(fn:()=>void,success:string)=>{try{fn();toast.success(success)}catch(error){toast.error(error instanceof Error?error.message:'Có lỗi xảy ra.')}}

export function SeedPicker({plot,onClose}:{plot?:FarmPlot;onClose:()=>void}){
 const {player,plantCrop}=useGameStore(), seeds=useGameStore(s=>s.inventory)
 const choose=(cropId:string)=>{const owned=seeds.find(i=>i.itemType==='seed'&&i.referenceId===cropId)?.quantity??0;run(()=>plantCrop(plot!.id,cropId,owned===0),owned?'Đã gieo hạt! 🌱':'Đã mua nhanh và gieo hạt! 🌱');onClose()}
 return <Modal open={!!plot} title="Chọn hạt giống" onClose={onClose} wide><div className="seed-grid">{crops.map(c=>{const owned=seeds.find(i=>i.itemType==='seed'&&i.referenceId===c.id)?.quantity??0,locked=player.level<c.requiredLevel;return <button key={c.id} className={`seed-card ${locked?'disabled':''}`} disabled={locked} onClick={()=>choose(c.id)}><span className="item-icon">{c.icon}</span><div className="seed-info"><b>{c.name}</b><small><Clock3/> {formatDuration(c.growthDurationSeconds)}</small><small>Thu {c.harvestQuantityMin}–{c.harvestQuantityMax} · +{c.xpReward} XP</small><small>Lãi dự kiến <em>+{formatNumber(c.sellPrice*c.harvestQuantityMin-c.seedPrice)}</em></small></div><div className="seed-price">{locked?<><LockKeyhole/> Cấp {c.requiredLevel}</>:owned?<><span>Có {owned}</span><strong>Gieo</strong></>:<><span>{formatNumber(c.seedPrice)} 🪙</span><strong>Mua & gieo</strong></>}</div></button>})}</div></Modal>
}

export function CropPanel({plot,now,onClose}:{plot?:FarmPlot;now:number;onClose:()=>void}){
 const {inventory,applyFertilizer,harvestCrop}=useGameStore(),instance=plot?.cropInstance,crop=instance?cropById(instance.cropId):undefined,growth=instance&&crop?getCropGrowthState(instance,crop,now):undefined
 if(!instance||!crop||!growth)return null
 const harvest=()=>{try{const r=harvestCrop(plot!.id);toast.success(`Thu hoạch ${r.quantity} ${crop.name}, +${r.xp} XP!`);if(r.leveledUp)toast.success('Lên cấp! 🎉');onClose()}catch(e){toast.error(e instanceof Error?e.message:'Không thể thu hoạch')}}
 const fertilize=(id:string)=>{try{const r=applyFertilizer(plot!.id,id);toast.success(r?`Đã rút ngắn ${formatDuration(r)}!`:'Cây đã gần chín.');}catch(e){toast.error(e instanceof Error?e.message:'Không thể bón phân')}}
 return <Modal open title={crop.name} onClose={onClose}><div className="crop-detail"><div className={`big-crop ${growth.isReadyToHarvest?'ripe':''}`}>{growth.currentStage.icon}</div><h3>{growth.currentStage.label}</h3><div className="large-progress"><i style={{width:`${growth.growthPercent}%`}}/></div><p>{growth.isReadyToHarvest?'Cây đã chín mọng và sẵn sàng!':`Còn ${formatRemainingTime(growth.remainingSeconds)} · ${Math.floor(growth.growthPercent)}%`}</p>{growth.isReadyToHarvest?<button className="primary harvest" onClick={harvest}>🧺 Thu hoạch ngay</button>:<><h4><Leaf/> Bón phân tăng tốc</h4><div className="fert-list">{fertilizers.map(f=>{const count=inventory.find(i=>i.itemType==='fertilizer'&&i.referenceId===f.id)?.quantity??0,used=instance.fertilizerUsage.filter(u=>u.fertilizerId===f.id).length;return <button key={f.id} disabled={!count||used>=f.maxUsesPerCrop} onClick={()=>fertilize(f.id)}><span>{f.icon}</span><div><b>{f.name}</b><small>{f.description}</small></div><em>x{count}</em></button>})}</div></>}</div></Modal>
}

export function UnlockPanel({plot,onClose}:{plot?:FarmPlot;onClose:()=>void}){const {player,unlockPlot}=useGameStore();if(!plot)return null;const canLevel=player.level>=plot.requiredLevel,canGold=player.gold>=plot.unlockPrice;return <Modal open title={`Mở luống đất #${plot.plotNumber}`} onClose={onClose}><div className="confirm-panel"><div className="unlock-art">🔐</div><p>Mở rộng nông trại để trồng thêm nhiều cây?</p><div className={`requirement ${canLevel?'ok':''}`}>{canLevel?<Check/>:<LockKeyhole/>} Cấp {plot.requiredLevel}</div><div className={`requirement ${canGold?'ok':''}`}><Coins/> {formatNumber(plot.unlockPrice)} vàng</div><button className="primary" disabled={!canLevel||!canGold} onClick={()=>{run(()=>unlockPlot(plot.id),'Mở đất thành công! 🎊');onClose()}}>Mở luống đất</button></div></Modal>}

export function ShopPanel({open,initialTab='seed',onClose}:{open:boolean;initialTab?:'seed'|'fertilizer';onClose:()=>void}){
 const {player,buyItem}=useGameStore();const items=initialTab==='seed'?crops:fertilizers
 return <Modal open={open} title={initialTab==='seed'?'Cửa hàng hạt giống':'Quầy phân bón'} onClose={onClose} wide><div className="shop-banner"><div><b>{initialTab==='seed'?'Hạt giống tươi mới':'Chăm cây lớn thật nhanh'}</b><span>Mua sắm thông minh, mùa vụ bội thu!</span></div><div>{initialTab==='seed'?'🌻':'🌿'}</div></div><div className="shop-grid">{items.map(item=>{const isCrop='seedPrice'in item,locked=isCrop&&player.level<item.requiredLevel,price=isCrop?item.seedPrice:(item.priceGold??item.priceDiamonds??0),diamond=!isCrop&&!!item.priceDiamonds;return <article key={item.id} className={locked?'disabled':''}><span className="item-icon">{item.icon}</span><div><b>{item.name}</b><small>{item.description}</small>{isCrop&&<small><Clock3/> {formatDuration(item.growthDurationSeconds)}</small>}</div><div className="shop-footer"><Qty type={initialTab} id={item.id}/>{locked?<span><LockKeyhole/> Cấp {item.requiredLevel}</span>:<button onClick={()=>run(()=>buyItem(initialTab,item.id),`Đã mua ${item.name}!`)}><ShoppingCart/> {formatNumber(price)} {diamond?'💎':'🪙'}</button>}</div></article>})}</div></Modal>
}

export function InventoryPanel({open,onClose}:{open:boolean;onClose:()=>void}){const {inventory,player,sellProduce}=useGameStore(),total=inventory.reduce((s,i)=>s+i.quantity,0);return <Modal open={open} title="Kho nông sản" onClose={onClose} wide><div className="capacity"><Backpack/><div><b>{total}/{player.inventoryCapacity}</b><span>Sức chứa kho</span></div><i><em style={{width:`${total/player.inventoryCapacity*100}%`}}/></i></div>{!inventory.length?<div className="empty-state"><PackageOpen/><b>Kho đang trống</b><span>Hãy trồng và thu hoạch cây đầu tiên!</span></div>:<div className="inventory-grid">{inventory.map(item=>{const crop=cropById(item.referenceId),fert=fertilizerById(item.referenceId),name=crop?.name??fert?.name??item.referenceId,icon=crop?.icon??fert?.icon??'📦';return <article key={item.id}><span>{icon}</span><div><b>{name}</b><small>{item.itemType==='seed'?'Hạt giống':item.itemType==='produce'?'Nông sản':'Phân bón'}</small></div><strong>x{item.quantity}</strong>{item.itemType==='produce'&&crop&&<button onClick={()=>{const gold=sellProduce(crop.id,item.quantity);toast.success(`Đã bán, nhận ${formatNumber(gold)} vàng!`)}}>Bán hết · {formatNumber(crop.sellPrice*item.quantity)} 🪙</button>}</article>})}</div>}</Modal>}

export function MissionsPanel({open,onClose}:{open:boolean;onClose:()=>void}){const stats=useGameStore(s=>s.stats);const missions=[['Gieo mầm đầu tiên',stats.planted,1,'🌱'],['Thu hoạch 10 nông sản',stats.harvested,10,'🧺'],['Bán 8 nông sản',stats.sold,8,'🪙'],['Mở rộng nông trại',stats.plotsUnlocked,1,'🔓'] ] as const;return <Modal open={open} title="Nhiệm vụ hôm nay" onClose={onClose}><div className="mission-list">{missions.map(([name,current,target,icon])=>{const done=current>=target;return <article key={name} className={done?'done':''}><span>{icon}</span><div><b>{name}</b><div><i style={{width:`${Math.min(100,current/target*100)}%`}}/></div><small>{Math.min(current,target)}/{target}</small></div>{done?<Check/>:<Star/>}</article>})}</div></Modal>}

export function SettingsPanel({open,onClose}:{open:boolean;onClose:()=>void}){const {player,updateSettings,resetGame}=useGameStore();return <Modal open={open} title="Cài đặt" onClose={onClose}><div className="settings"><label><span>🎵 Nhạc nền</span><input type="checkbox" checked={player.settings.music} onChange={e=>updateSettings({music:e.target.checked})}/></label><label><span>🔊 Hiệu ứng âm thanh</span><input type="checkbox" checked={player.settings.sound} onChange={e=>updateSettings({sound:e.target.checked})}/></label><label><span>🪶 Giảm chuyển động</span><input type="checkbox" checked={player.settings.reducedMotion} onChange={e=>updateSettings({reducedMotion:e.target.checked})}/></label><button className="secondary" onClick={()=>useGameStore.getState().setTutorialStep(0)}>Xem lại hướng dẫn</button><button className="danger" onClick={()=>{if(confirm('Bước 1/2: Bạn muốn chơi lại từ đầu?')&&confirm('Bước 2/2: Mọi tiến trình sẽ bị xóa. Xác nhận?')){resetGame();onClose();toast.success('Đã tạo nông trại mới.')}}}><RotateCcw/> Chơi lại từ đầu</button><p className="security-note">Dữ liệu MVP được lưu cục bộ trên thiết bị và có thể bị chỉnh sửa. Khi chuyển sang máy chủ, giao dịch sẽ được xác thực phía backend.</p></div></Modal>}

export function DailyPanel({open,onClose}:{open:boolean;onClose:()=>void}){return <Modal open={open} title="Quà chăm chỉ" onClose={onClose}><div className="daily"><Sparkles/><h3>Chào buổi sáng, nông dân!</h3><p>Chuỗi đăng nhập: <b>1 ngày</b></p><div className="reward-box"><Coins/> 100 vàng <Minus/> <Gem/> 1 kim cương</div><button className="primary" onClick={()=>{toast.success('Quà ngày sẽ có trong bản cập nhật tiếp theo!');onClose()}}>Xem phần thưởng</button></div></Modal>}
