import { Backpack, Check, Clock3, Coins, Leaf, LockKeyhole, PackageOpen, RotateCcw, ShoppingCart, Sparkles, Star } from 'lucide-react'
import { toast } from 'sonner'
import { crops } from '../config/crops'
import { fertilizers } from '../config/fertilizers'
import { useGameStore } from '../store/gameStore'
import type { FarmPlot } from '../types/game'
import { cropById } from '../config/crops'
import { fertilizerById } from '../config/fertilizers'
import { formatNumber } from '../utils/currency'
import { getCropGrowthState } from '../utils/cropGrowth'
import { formatDuration, formatRemainingTime } from '../utils/time'
import { Modal } from './Modal'
import { useEffect, useMemo, useState, type CSSProperties } from 'react'
import { SoundManager } from '../services/soundService'
import { triggerHapticFeedback } from '../utils/haptics'
import { animateFarmer } from '../hooks/useFarmCharacter'
import { foodById } from '../config/npcShops'
import { getCropEconomy } from '../utils/cropEconomy'
import { RarityLabel, TraitBadges } from './GeneticsPanels'
import { rarityConfig } from '../config/geneticsConfig'
import { buyGeneticSeedOnServer, harvestCropOnServer, plantCropOnServer } from '../services/geneticsApi'
import { useAuth } from '../contexts/AuthContext'

const Qty=({type,id}:{type:'seed'|'produce'|'fertilizer';id:string})=>{const n=useGameStore(s=>s.inventory.find(i=>i.itemType===type&&i.referenceId===id)?.quantity??0);return <span className="qty">x{n}</span>}
const errorMessage=(error:unknown,fallback:string)=>{
 const raw=error instanceof Error?error.message:error&&typeof error==='object'&&'message'in error?String(error.message):''
 const messages:Record<string,string>={
  CROP_NOT_FOUND:'Không tìm thấy dữ liệu cây trên máy chủ. Hãy đồng bộ rồi thử lại.',
  CROP_NOT_READY:'Cây chưa chín theo thời gian máy chủ.',
  INVENTORY_FULL:'Kho đã đầy! Hãy bán bớt nông sản.',
  SAVE_NOT_FOUND:'Chưa có bản lưu cloud. Hãy đồng bộ lại game.',
  NOT_ENOUGH_GOLD:'Bạn không đủ vàng.',
 }
 return messages[raw]??(raw||fallback)
}
const run=(fn:()=>void,success:string)=>{try{fn();toast.success(success)}catch(error){toast.error(errorMessage(error,'Có lỗi xảy ra.'))}}

export function SeedPicker({plot,onClose}:{plot?:FarmPlot;onClose:()=>void}){
 const auth=useAuth(),{player,plantCrop,replaceGameData}=useGameStore(),seeds=useGameStore(s=>s.inventory),allSpecialSeeds=useGameStore(s=>s.specialSeeds),specialSeeds=useMemo(()=>allSpecialSeeds.filter(seed=>seed.status==='inventory'),[allSpecialSeeds]),[busy,setBusy]=useState(false)
 const choose=async(cropId:string,seedInstanceId?:string)=>{if(busy)return;setBusy(true);const owned=seeds.find(i=>i.itemType==='seed'&&i.referenceId===cropId)?.quantity??0;try{if(auth.configured){await auth.syncNow();const response=await plantCropOnServer(plot!.plotNumber,cropId,seedInstanceId);replaceGameData(response.state)}else plantCrop(plot!.id,cropId,!seedInstanceId&&owned===0,seedInstanceId);SoundManager.play('plant',player.settings.sound,player.settings.volume);triggerHapticFeedback('light',player.settings.haptics);animateFarmer('plant',plot!.plotNumber);toast.success(`Đã trồng ${cropById(cropId)?.name}!`);onClose()}catch(e){toast.error(errorMessage(e,'Không thể gieo hạt'))}finally{setBusy(false)}}
 return <Modal open={!!plot} title="Chọn hạt giống" onClose={onClose} wide>{specialSeeds.length>0&&<><h3 className="section-title">🧬 Hạt giống đặc biệt</h3><div className="special-seed-grid">{specialSeeds.map(seed=>{const crop=cropById(seed.cropId);return <button key={seed.id} className={`special-seed rarity-${seed.rarity}`} style={{'--rarity':rarityConfig[seed.rarity].color} as CSSProperties} onClick={()=>choose(seed.cropId,seed.id)}><span className="item-icon">{crop?.icon??'🌱'}</span><div><b>{seed.hybridId?crop?.name+' lai':crop?.name}</b><RarityLabel rarity={seed.rarity}/><TraitBadges traits={seed.traits}/><small>Thế hệ G{seed.generation} · {seed.source==='hybrid'?'Hạt lai':'Hạt đặc biệt'}</small></div><strong>Gieo hạt này</strong></button>})}</div></>}<h3 className="section-title">🌰 Hạt giống cơ bản</h3><div className="seed-grid">{crops.map(c=>{const owned=seeds.find(i=>i.itemType==='seed'&&i.referenceId===c.id)?.quantity??0,locked=player.level<c.requiredLevel;return <button key={c.id} className={`seed-card ${locked?'disabled':''}`} disabled={locked} onClick={()=>choose(c.id)}><span className="item-icon">{c.icon}</span><div className="seed-info"><b>{c.name}</b><small><Clock3/> {formatDuration(c.growthDurationSeconds)}</small><small>Thu {c.harvestQuantityMin}–{c.harvestQuantityMax} · +{c.xpReward} XP</small><small>Lãi dự kiến <em>+{formatNumber(c.sellPrice*c.harvestQuantityMin-c.seedPrice)}</em></small></div><div className="seed-price">{locked?<><LockKeyhole/> Cấp {c.requiredLevel}</>:owned?<><span>Có {owned}</span><strong>Gieo</strong></>:<><span>{formatNumber(c.seedPrice)} 🪙</span><strong>Mua & gieo</strong></>}</div></button>})}</div></Modal>
}

export function CropPanel({plot,now,onClose}:{plot?:FarmPlot;now:number;onClose:()=>void}){
 const auth=useAuth(),{inventory,applyFertilizer,harvestCrop,careForCrop,player,replaceGameData}=useGameStore(),[busy,setBusy]=useState(false),instance=plot?.cropInstance,crop=instance?cropById(instance.cropId):undefined,growth=instance&&crop?getCropGrowthState(instance,crop,now):undefined
 useEffect(()=>setBusy(false),[instance?.id])
 if(!instance||!crop||!growth)return null
 const harvest=async()=>{if(busy)return;setBusy(true);try{if(auth.configured){await auth.syncNow();const r=await harvestCropOnServer(plot!.plotNumber);replaceGameData(r.state);SoundManager.play(r.hybridSeed?'lucky':'harvest',player.settings.sound,player.settings.volume);triggerHapticFeedback(r.hybridSeed?'success':'medium',player.settings.haptics);animateFarmer(r.hybridSeed?'celebrate':'harvest',plot!.plotNumber);toast.success([`+${r.quantity} ${crop.name} · +${r.xp} XP`,r.giantQuantity?'Xuất hiện quả khổng lồ!':'',r.hybridSeed?'Lai giống thành công!':r.hybridAttempted?'Chưa tạo được hạt lai':'',r.pending?'Hạt lai đã chuyển vào Hạt đang chờ.':''].filter(Boolean).join(' · '),{duration:r.hybridSeed?6000:3500})}else{const r=harvestCrop(plot!.id);SoundManager.play(r.genetics.hybridSeed?'lucky':r.yield.isPerfectHarvest||r.yield.isLuckyHarvest?'lucky':'harvest',player.settings.sound,player.settings.volume);triggerHapticFeedback(r.yield.isLuckyHarvest?'success':'medium',player.settings.haptics);animateFarmer(r.leveledUp?'celebrate':'harvest',plot!.plotNumber);toast.success([`+${r.quantity} ${crop.name} · +${r.xp} XP`,...r.genetics.traitMessages,r.genetics.hybridAttempted&&!r.genetics.hybridSeed?'Chưa tạo được hạt lai':''].filter(Boolean).join(' · '))}onClose()}catch(e){toast.error(errorMessage(e,'Không thể thu hoạch'))}finally{setBusy(false)}}
 const fertilize=(id:string)=>{if(busy)return;setBusy(true);try{const r=applyFertilizer(plot!.id,id);SoundManager.play('fertilize',player.settings.sound,player.settings.volume);animateFarmer('fertilize',plot!.plotNumber);toast.success(r?`-${formatDuration(r)} thời gian còn lại!`:'Cây đã gần chín.')}catch(e){toast.error(e instanceof Error?e.message:'Không thể bón phân')}finally{window.setTimeout(()=>setBusy(false),350)}}
 const care=(action:'water'|'weed'|'pest')=>{try{careForCrop(plot!.id,action);SoundManager.play(action,player.settings.sound,player.settings.volume);triggerHapticFeedback('light',player.settings.haptics);animateFarmer(action,plot!.plotNumber);toast.success(action==='water'?'Đã tưới mát cho cây!':action==='weed'?'Đã nhổ sạch cỏ!':'Đã bắt hết sâu!')}catch(e){toast.error(e instanceof Error?e.message:'Không thể chăm cây')}}
 return <Modal open title={crop.name} onClose={onClose}><div className="crop-detail"><div className={`big-crop ${growth.isReadyToHarvest?'ripe':''}`}>{growth.currentStage.icon}</div><h3>{growth.currentStage.label}</h3>{instance.rarity&&instance.rarity!=='common'&&<div className="crop-genetics"><RarityLabel rarity={instance.rarity}/><TraitBadges traits={instance.traits??[]}/><small>Thế hệ G{instance.generation??0}{instance.hybridId?' · Cây lai':''}</small></div>}<div className="large-progress"><i style={{width:`${growth.growthPercent}%`}}/></div><p>{growth.isReadyToHarvest?'Cây đã chín mọng và sẵn sàng!':`Còn ${formatRemainingTime(growth.remainingSeconds)} · ${Math.floor(growth.growthPercent)}%`}</p>{growth.isReadyToHarvest?<button className="primary harvest" disabled={busy} onClick={harvest}>🧺 Thu hoạch ngay</button>:<><div className="care-actions"><button onClick={()=>care('water')}>💧<span>Tưới nước</span></button><button className={instance.care?.weeds?'alert':''} disabled={!instance.care?.weeds} onClick={()=>care('weed')}>🌿<span>Nhổ cỏ</span></button><button className={instance.care?.pests?'alert':''} disabled={!instance.care?.pests} onClick={()=>care('pest')}>🐛<span>Bắt sâu</span></button></div><h4><Leaf/> Bón phân tăng tốc</h4><div className="fert-list">{fertilizers.map(f=>{const count=inventory.find(i=>i.itemType==='fertilizer'&&i.referenceId===f.id)?.quantity??0,used=instance.fertilizerUsage.filter(u=>u.fertilizerId===f.id).length;return <button key={f.id} disabled={busy||!count||used>=f.maxUsesPerCrop} onClick={()=>fertilize(f.id)}><span>{f.icon}</span><div><b>{f.name}</b><small>{f.description}</small></div><em>x{count}</em></button>})}</div></>}</div></Modal>
}

export function UnlockPanel({plot,onClose}:{plot?:FarmPlot;onClose:()=>void}){const {player,unlockPlot}=useGameStore();if(!plot)return null;const canLevel=player.level>=plot.requiredLevel,canGold=player.gold>=plot.unlockPrice;return <Modal open title={`Mở luống đất #${plot.plotNumber}`} onClose={onClose}><div className="confirm-panel"><div className="unlock-art">🔐</div><p>Mở rộng nông trại để trồng thêm nhiều cây?</p><div className={`requirement ${canLevel?'ok':''}`}>{canLevel?<Check/>:<LockKeyhole/>} Cấp {plot.requiredLevel}</div><div className={`requirement ${canGold?'ok':''}`}><Coins/> {formatNumber(plot.unlockPrice)} vàng</div><button className="primary" disabled={!canLevel||!canGold} onClick={()=>{run(()=>unlockPlot(plot.id),'Mở đất thành công! 🎊');onClose()}}>Mở luống đất</button></div></Modal>}

export function ShopPanel({open,initialTab='seed',onClose}:{open:boolean;initialTab?:'seed'|'fertilizer';onClose:()=>void}){
 const auth=useAuth(),{player,buyItem,replaceGameData}=useGameStore();const items=initialTab==='seed'?crops:fertilizers
 const buySpecial=async(cropId:string)=>{try{await auth.syncNow();const result=await buyGeneticSeedOnServer(cropId);replaceGameData(result.state);toast.success('Đã nhận một hạt giống có đặc tính!')}catch(error){toast.error(errorMessage(error,'Không thể mua hạt đặc biệt'))}}
 return <Modal open={open} title={initialTab==='seed'?'Cửa hàng hạt giống':'Quầy phân bón'} onClose={onClose} wide><div className="shop-banner"><div><b>{initialTab==='seed'?'Hạt giống tươi mới':'Chăm cây lớn thật nhanh'}</b><span>Mua sắm thông minh, mùa vụ bội thu!</span></div><div>{initialTab==='seed'?'🌻':'🌿'}</div></div><div className="shop-grid">{items.map(item=>{const isCrop='seedPrice'in item,locked=isCrop&&player.level<item.requiredLevel,price=isCrop?item.seedPrice:item.priceGold,economy=isCrop?getCropEconomy(item):undefined;return <article key={item.id} className={locked?'disabled':''}><span className="item-icon">{item.icon}</span><div><b>{item.name}</b><small>{item.description}</small>{isCrop&&<small><Clock3/> {formatDuration(item.growthDurationSeconds)}</small>}{isCrop&&economy&&<div className="crop-economy"><span><b>Thu hoạch</b><em>{item.minHarvestQuantity}–{item.maxHarvestQuantity} · cơ bản {item.baseHarvestQuantity}</em></span><span><b>Giá bán</b><em>{formatNumber(economy.sellPricePerItem)} 🪙 / nông sản</em></span><span><b>Doanh thu</b><em>{formatNumber(economy.minRevenue)}–{formatNumber(economy.maxNormalRevenue)} 🪙</em></span><span className={economy.baseProfit>=0?'profit':'loss'}><b>Lãi cơ bản</b><strong>{economy.baseProfit>=0?'+':''}{formatNumber(economy.baseProfit)} 🪙</strong></span><small>Lãi thường: {economy.minProfit>=0?'+':''}{formatNumber(economy.minProfit)} đến {economy.maxNormalProfit>=0?'+':''}{formatNumber(economy.maxNormalProfit)} 🪙</small></div>}</div><div className="shop-footer"><Qty type={initialTab} id={item.id}/>{locked?<span><LockKeyhole/> Cấp {item.requiredLevel}</span>:<button onClick={()=>run(()=>buyItem(initialTab,item.id),`Đã mua ${item.name}!`)}><ShoppingCart/> {formatNumber(price)} 🪙</button>}</div>{isCrop&&!locked&&<button className="genetic-buy" onClick={()=>void buySpecial(item.id)}>🧬 Hạt chọn lọc · {formatNumber(item.seedPrice*3)} 🪙</button>}</article>})}</div></Modal>
}

export function InventoryPanel({open,onClose}:{open:boolean;onClose:()=>void}){const {inventory,player,sellProduce,consumeFood}=useGameStore(),total=inventory.reduce((s,i)=>s+i.quantity,0);return <Modal open={open} title="Kho nông sản" onClose={onClose} wide><div className="capacity"><Backpack/><div><b>{total}/{player.inventoryCapacity}</b><span>Sức chứa kho</span></div><i><em style={{width:`${total/player.inventoryCapacity*100}%`}}/></i></div>{!inventory.length?<div className="empty-state"><PackageOpen/><b>Kho đang trống</b><span>Hãy trồng và thu hoạch cây đầu tiên!</span></div>:<div className="inventory-grid">{inventory.map(item=>{const crop=cropById(item.referenceId),fert=fertilizerById(item.referenceId),food=foodById(item.referenceId),name=crop?.name??fert?.name??food?.name??item.referenceId,icon=crop?.icon??fert?.icon??food?.icon??(item.itemType==='gift'?'🎁':item.itemType==='tool'?'🛠️':'📦');return <article key={item.id}><span>{icon}</span><div><b>{name}</b><small>{item.itemType==='seed'?'Hạt giống':item.itemType==='produce'?'Nông sản':item.itemType==='fertilizer'?'Phân bón':item.itemType==='food'?'Món ăn':item.itemType==='gift'?'Quà tặng':'Dụng cụ'}</small></div><strong>x{item.quantity}</strong>{item.itemType==='produce'&&crop&&<button onClick={()=>{const gold=sellProduce(crop.id,item.quantity);toast.success(`Đã bán, nhận ${formatNumber(gold)} vàng!`)}}>Bán hết · {formatNumber(crop.sellPrice*item.quantity)} 🪙</button>}{item.itemType==='food'&&food&&<button onClick={()=>{try{consumeFood(food.id);toast.success(`Đã dùng ${food.name}! Buff có hiệu lực.`)}catch(error){toast.error(error instanceof Error?error.message:'Không thể dùng')}}}>Dùng món</button>}</article>})}</div>}</Modal>}

export function MissionsPanel({open,onClose}:{open:boolean;onClose:()=>void}){const stats=useGameStore(s=>s.stats);const missions=[['Gieo mầm đầu tiên',stats.planted,1,'🌱'],['Thu hoạch 10 nông sản',stats.harvested,10,'🧺'],['Bán 8 nông sản',stats.sold,8,'🪙'],['Mở rộng nông trại',stats.plotsUnlocked,1,'🔓'] ] as const;return <Modal open={open} title="Nhiệm vụ hôm nay" onClose={onClose}><div className="mission-list">{missions.map(([name,current,target,icon])=>{const done=current>=target;return <article key={name} className={done?'done':''}><span>{icon}</span><div><b>{name}</b><div><i style={{width:`${Math.min(100,current/target*100)}%`}}/></div><small>{Math.min(current,target)}/{target}</small></div>{done?<Check/>:<Star/>}</article>})}</div></Modal>}

export function SettingsPanel({open,onClose}:{open:boolean;onClose:()=>void}){const {player,updateSettings,resetGame}=useGameStore();return <Modal open={open} title="Cài đặt" onClose={onClose}><div className="settings"><label><span>🎵 Nhạc nền</span><input type="checkbox" checked={player.settings.music} onChange={e=>updateSettings({music:e.target.checked})}/></label><label><span>🔊 Hiệu ứng âm thanh</span><input type="checkbox" checked={player.settings.sound} onChange={e=>updateSettings({sound:e.target.checked})}/></label><label><span>📳 Phản hồi rung</span><input type="checkbox" checked={player.settings.haptics} onChange={e=>updateSettings({haptics:e.target.checked})}/></label><label><span>Âm lượng</span><input type="range" min="0" max="1" step=".05" value={player.settings.volume} onChange={e=>updateSettings({volume:Number(e.target.value)})}/></label><label><span>🪶 Giảm chuyển động</span><input type="checkbox" checked={player.settings.reducedMotion} onChange={e=>updateSettings({reducedMotion:e.target.checked})}/></label><button className="secondary" onClick={()=>useGameStore.getState().setTutorialStep(0)}>Xem lại hướng dẫn</button><button className="danger" onClick={()=>{if(confirm('Bước 1/2: Bạn muốn chơi lại từ đầu?')&&confirm('Bước 2/2: Mọi tiến trình sẽ bị xóa. Xác nhận?')){resetGame();onClose();toast.success('Đã tạo nông trại mới.')}}}><RotateCcw/> Chơi lại từ đầu</button><p className="security-note">Dữ liệu được lưu cục bộ và có thể đồng bộ Supabase; giao dịch cạnh tranh cần chuyển sang RPC phía máy chủ.</p></div></Modal>}

export function DailyPanel({open,onClose}:{open:boolean;onClose:()=>void}){return <Modal open={open} title="Quà chăm chỉ" onClose={onClose}><div className="daily"><Sparkles/><h3>Chào buổi sáng, nông dân!</h3><p>Chuỗi đăng nhập: <b>1 ngày</b></p><div className="reward-box"><Coins/> 100 vàng</div><button className="primary" onClick={()=>{toast.success('Quà ngày sẽ có trong bản cập nhật tiếp theo!');onClose()}}>Xem phần thưởng</button></div></Modal>}
